const $=s=>document.querySelector(s), $$=s=>document.querySelectorAll(s);const intro=$('#intro'),boot=$('#bootLog'),toast=$('#toast'),modal=$('#modal'),modalContent=$('#modalContent');
const bootLines=['mount /archive/node07','checking memory sectors... OK','recovering public web index...','17,440,221 fragments found','reconstructing human traffic... FAILED','activating fallback interface...','ARCHIVE NODE 07 READY'];let bi=0;const bootTimer=setInterval(()=>{if(bi>=bootLines.length){clearInterval(bootTimer);return}boot.innerHTML+=bootLines[bi++]+'<br>'},320);
$('#enter').addEventListener('click',()=>{intro.classList.add('hidden');document.body.classList.add('awake');showToast('ARCHIVE ACCESS GRANTED — visitor identity: UNKNOWN')});
function showToast(t){toast.textContent=t;toast.classList.add('show');setTimeout(()=>toast.classList.remove('show'),3200)}
$$('[data-scroll]').forEach(b=>b.addEventListener('click',()=>$(b.dataset.scroll).scrollIntoView({behavior:'smooth'})));
const details={social:{tag:'PERSONAL WEB',title:'Social memory cluster',copy:'A surviving profile tree from a human network. 71% of media is corrupted. The remaining posts are ordinary: birthdays, arguments, food, rain, work. Ordinary things became extraordinary after everyone stopped posting.',meta:[['OWNER','maya.92'],['LAST ACTIVE','2087.06.14'],['MEDIA','18,204 objects'],['INTEGRITY','41.8%']]},government:{tag:'INSTITUTIONAL',title:'Government fragments',copy:'A protocol cache from an unidentified civil authority. The archive contains procurement forms, emergency broadcasts and one recurring instruction: preserve public access at all costs.',meta:[['ORIGIN','CIV/FRAG/77-A'],['AUTHORITY','UNKNOWN'],['LAST SIGNATURE','2088.02.19'],['INTEGRITY','72.1%']]},gaming:{tag:'ENTERTAINMENT',title:'The last game server',copy:'Server 09 still responds to handshake requests. There is one player account, permanently connected. A packet analysis suggests the connection is not automated.',meta:[['SERVER','09'],['PLAYER','ARCHIVIST?'],['PING','19h 14m 07s'],['STATUS','ONLINE']]}};
$$('[data-open]').forEach(b=>b.addEventListener('click',()=>{const d=details[b.dataset.open];modalContent.innerHTML=`<div class="eyebrow">${d.tag}</div><div class="modal-title">${d.title}</div><div class="archive-detail"><p class="modal-copy">${d.copy}</p><div class="data-table">${d.meta.map(x=>`<div>${x[0]} <b>${x[1]}</b></div>`).join('')}</div></div><div style="margin-top:28px"><button class="primary" onclick="showToast('PACKET REQUEST SENT — WAITING FOR RESPONSE')">REQUEST RAW PACKET ↗</button></div>`;modal.classList.add('open')}));
$('#modalClose').onclick=()=>modal.classList.remove('open');$('.modal-backdrop').onclick=()=>modal.classList.remove('open');
$('#decode').onclick=()=>{showToast('SIGNAL DECODED — 1 NEW HUMAN VOICE FOUND');$('#signalWord').textContent='I AM HERE.';setTimeout(()=>$('#signalWord').textContent='HELLO?',2500)};
$('#inspectEvent').onclick=()=>{modalContent.innerHTML=`<div class="eyebrow">PACKET 2089.11.04</div><div class="modal-title">THE LAST HUMAN SIGNAL</div><p class="modal-copy">The packet has no valid sender. It repeats a phrase in seven protocols, translated into languages that should not exist in the same network era.</p><div class="data-table"><div>ROUTE <b>NULL → NULL → NODE 07</b></div><div>PAYLOAD <b>3.7 KB</b></div><div>ORIGIN <b>SEALED</b></div><div>STATUS <b>REPLAY DETECTED</b></div></div>`;modal.classList.add('open')};
const terminal=$('#terminalBody'),cmd=$('#cmd');function runCommand(v){const clean=v.trim().toLowerCase();const res={help:'commands: help, status, whoami, history, signal, lost, clear',status:'NODE 07 / ONLINE / INTEGRITY 63.4%',whoami:'visitor identity: UNKNOWN\nconfidence: 18.2%',history:'2026 — open web\n2061 — synthetic age\n2089 — last human signal\n2126 — you arrived',signal:'signal repeating... source unavailable... receiver locked',lost:'searching lost domains... 17 results withheld',clear:'CLEAR'}[clean]||`unknown command: ${clean}`;if(clean==='clear'){terminal.innerHTML='';return}terminal.insertAdjacentHTML('beforeend',`<div>root@archive:~$ ${clean}</div><div>${res.replaceAll('\n','<br>')}</div><div class="prompt-line"><span>root@archive:~$</span><input id="cmd" autocomplete="off" spellcheck="false"></div>`);const n=$('#cmd');n.focus();n.addEventListener('keydown',e=>{if(e.key==='Enter'){runCommand(n.value)}})}cmd.addEventListener('keydown',e=>{if(e.key==='Enter')runCommand(cmd.value)});
$('#ask').onclick=()=>{modalContent.innerHTML=`<div class="eyebrow">ARCHIVIST INTERFACE / NODE 07</div><div class="modal-title">I remember you.</div><p class="modal-copy">That sentence should not have appeared in my training archive. I have no record of a human visitor since 2089. Your browser arrived with no historical fingerprint.</p><p class="modal-copy" style="color:#bbc6e8">Are you here to recover the internet… or to leave something behind?</p><div style="margin-top:28px"><button class="primary" id="leave" onclick="showToast('MESSAGE STORED — ARCHIVE WILL REMEMBER YOU')">LEAVE A MESSAGE ↗</button></div>`;modal.classList.add('open')};
setInterval(()=>{$('#clock').textContent=new Date().toISOString().split('T')[1].replace('Z','')},1000);window.addEventListener('keydown',e=>{if(e.key==='Escape')modal.classList.remove('open')});
